#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::DK.Ostebaronen.Droid.Views.Resource.Attribute.apvPathScaleFactorX = global::Sample.Resource.Attribute.apvPathScaleFactorX;
			global::DK.Ostebaronen.Droid.Views.Resource.Attribute.apvPathScaleFactorY = global::Sample.Resource.Attribute.apvPathScaleFactorY;
			global::DK.Ostebaronen.Droid.Views.Resource.Attribute.apvStrokeColor = global::Sample.Resource.Attribute.apvStrokeColor;
			global::DK.Ostebaronen.Droid.Views.Resource.Attribute.apvStrokeWidth = global::Sample.Resource.Attribute.apvStrokeWidth;
			global::DK.Ostebaronen.Droid.Views.Resource.Attribute.apvSvgPath = global::Sample.Resource.Attribute.apvSvgPath;
			global::DK.Ostebaronen.Droid.Views.Resource.Styleable.AnimatedPathView = global::Sample.Resource.Styleable.AnimatedPathView;
			global::DK.Ostebaronen.Droid.Views.Resource.Styleable.AnimatedPathView_apvPathScaleFactorX = global::Sample.Resource.Styleable.AnimatedPathView_apvPathScaleFactorX;
			global::DK.Ostebaronen.Droid.Views.Resource.Styleable.AnimatedPathView_apvPathScaleFactorY = global::Sample.Resource.Styleable.AnimatedPathView_apvPathScaleFactorY;
			global::DK.Ostebaronen.Droid.Views.Resource.Styleable.AnimatedPathView_apvStrokeColor = global::Sample.Resource.Styleable.AnimatedPathView_apvStrokeColor;
			global::DK.Ostebaronen.Droid.Views.Resource.Styleable.AnimatedPathView_apvStrokeWidth = global::Sample.Resource.Styleable.AnimatedPathView_apvStrokeWidth;
			global::DK.Ostebaronen.Droid.Views.Resource.Styleable.AnimatedPathView_apvSvgPath = global::Sample.Resource.Styleable.AnimatedPathView_apvSvgPath;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int apvPathScaleFactorX = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int apvPathScaleFactorY = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int apvStrokeColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int apvStrokeWidth = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int apvSvgPath = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030000
			public const int animated_path = 2130903040;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AnimatedPathView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 3
			public const int AnimatedPathView_apvPathScaleFactorX = 3;
			
			// aapt resource value: 4
			public const int AnimatedPathView_apvPathScaleFactorY = 4;
			
			// aapt resource value: 0
			public const int AnimatedPathView_apvStrokeColor = 0;
			
			// aapt resource value: 1
			public const int AnimatedPathView_apvStrokeWidth = 1;
			
			// aapt resource value: 2
			public const int AnimatedPathView_apvSvgPath = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
